language:  python
python: "3.7"

env:
   - ADDON_ID=script.service.hue
     BRANCH=matrix
     REPO=repo-scripts

# command to install dependencies
install:
  - pip install kodi-addon-checker

script:
  - kodi-addon-checker --branch $BRANCH $ADDON_ID

before_deploy:
  - pip install  git+https://github.com/romanvm/kodi-addon-submitter.git
  - submit-addon -s -z $ADDON_ID
  - export RELEASE_ZIP=$(ls *.zip)


deploy:
  - provider: releases
    api_key: $GH_TOKEN
    overwrite: true
    file_glob: true
    file: $RELEASE_ZIP
    skip_cleanup: true
    draft: false
    on:
      branch: master
      tags: true

  - provider: script
    script: submit-addon -s $ADDON_ID -b $BRANCH -r $REPO --push-branch
    on:
      tags: true

#notifications:
#    webhooks: https://www.travisbuddy.com/