name: Sync addon metadata translations

on:
  push:
    branches: [ main ]
    paths:
      - '**addon.xml'
      - '**resource.language.**strings.po'

jobs:
  default:
    if: github.repository == 'zim514/script.service.hue'
    runs-on: ubuntu-latest

    strategy:

      fail-fast: false
      matrix:
        python-version: [ 3.9 ]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          path: project
          fetch-depth: 0

      - name: Checkout sync_addon_metadata_translations repository
        uses: actions/checkout@v6
        with:
          repository: xbmc/sync_addon_metadata_translations
          path: sync_addon_metadata_translations

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install sync_addon_metadata_translations/

      - name: Run sync-addon-metadata-translations
        run: |
          sync-addon-metadata-translations
        working-directory: ./project/script.service.hue

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          repository: project
          commit_message: Sync of addon metadata translations triggered by ${{ github.sha }}
          add_options: '--all'
